# Generated by Django 6.1.1 on 2026-09-15 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "main_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="myapp.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sub Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("unique_code", models.CharField(max_length=50, unique=True)),
                (
                    "dimensions",
                    models.CharField(help_text="e.g., 120x60x45 cm", max_length=100),
                ),
                (
                    "cpm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost/Cubic Per Meter",
                        max_digits=10,
                    ),
                ),
                ("description", models.TextField()),
                ("image_1", models.ImageField(upload_to="products/")),
                (
                    "image_2",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "image_3",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "image_4",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "image_5",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "main_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.category"
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.subcategory",
                    ),
                ),
            ],
        ),
    ]
