# Generated by Django 6.1.1 on 2026-09-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_category_subcategory_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this box to hide the product from the website without deleting it.",
            ),
        ),
    ]
