# Generated by Django 6.1.1 on 2026-09-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_inquiry_inquiryitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiryitem",
            name="quoted_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Custom price set by admin for this inquiry item.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
